#!/usr/bin/env python3
"""Apply the STR content expansion after legacy page generators. Safe to rerun."""
from pathlib import Path
import html, json, re
from collections import defaultdict
from refresh_trust_content import shell
from build_new_content import rebuild_sitemap, update_blog_index
from stratum_render import AE_BOOKING, BASE_URL
ROOT=Path(__file__).resolve().parent
E=html.escape
TODAY='2026-09-27'
SOURCES='<p>Technical references: <a href="https://www.irs.gov/publications/p946">IRS Publication 946</a>, <a href="https://www.irs.gov/publications/p925">Publication 925</a>, and <a href="https://www.irs.gov/publications/p527">Publication 527</a>. Educational information; implementation depends on your facts and tax year.</p>'

def links(items):
    return '<ul>'+''.join(f'<li><a href="/{p}/">{E(t)}</a></li>' for p,t in items)+'</ul>'

def page(path,title,desc,heading,body,article=False,area=None):
    content=f'<main class="article"><div class="breadcrumbs"><a href="/">Home</a> &raquo; <a href="/{"blog" if article else "locations"}/">{"Blog" if article else "Service areas"}</a></div><h1>{E(heading)}</h1><p>{E(desc)}</p>{body}<div class="cta-banner"><h2>Discuss your property with AE Tax Advisors</h2><p>Bring your acquisition records, rental-use history, and current depreciation schedule to discuss whether a Stratum study fits.</p><a class="btn btn-gold" href="{AE_BOOKING}">Book a discovery call &rarr;</a></div></main>'
    out=shell(title,desc,path,content,depth=len(path.split('/')))
    out=out.replace('"dateModified":"2026-09-22"',f'"dateModified":"{TODAY}"')
    url=f'{BASE_URL}/{path}/'
    graph=[{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE_URL+'/'},{'@type':'ListItem','position':2,'name':heading,'item':url}]}]
    if article:
        graph.append({'@type':'BlogPosting','headline':heading,'datePublished':TODAY,'dateModified':TODAY,'author':{'@type':'Organization','name':'Stratum Cost Segregation','url':BASE_URL},'mainEntityOfPage':url})
    if area:
        graph.append({'@type':'Service','name':heading,'serviceType':'Short-term rental cost segregation','provider':{'@type':'Organization','name':'Stratum Cost Segregation','url':BASE_URL},'areaServed':{'@type':'Place','name':area},'url':url})
    out=out.replace('</head>','<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@graph':graph})+'</script>\n</head>')
    dest=ROOT/path/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(out)

def metadata(text,title,desc):
    text=re.sub(r'<title>.*?</title>',f'<title>{E(title)}</title>',text,count=1)
    for key,value in [('description',desc),('og:title',title),('og:description',desc),('twitter:title',title),('twitter:description',desc)]:
        text=re.sub(r'(<meta (?:name|property)="'+key+r'" content=")[^"]*(")',lambda m:m[1]+E(value,quote=True)+m[2],text)
    def schema(m):
        obj=json.loads(m[1]); nodes=obj.get('@graph',[obj])
        for n in nodes:
            if n.get('@type')=='WebPage':n.update(name=title,description=desc)
            if n.get('@type')=='WebSite':n.pop('potentialAction',None)
        return '<script type="application/ld+json">'+json.dumps(obj,separators=(',',':'))+'</script>'
    return re.sub(r'<script type="application/ld\+json">(.*?)</script>',schema,text,flags=re.S)

# Each market carries a distinct ownership / record-reconciliation scenario.
MARKETS=[
('boston-ma','Boston','MA','Condominium interests and older multifamily conversions','For a furnished Boston condominium, begin with the unit deed and association documents. Separate the unit interior from common systems and reconcile any renovation paid directly by the owner. An assessment or association budget does not by itself establish a separately depreciable asset for the unit owner.','Request the unit closing statement, improvement approvals, appliance invoices, and assessment descriptions. Ask whether a quoted study covers only the unit or also assumes an ownership share in common property.','A condo purchase includes furniture under a separate bill of sale. Reconcile that schedule before assigning any purchase basis to appliances so those costs are not counted twice.'),
('washington-dc','Washington','DC','Rowhouse layouts and owner-occupied portions','A Washington rowhouse may combine owner space, a furnished guest level, and shared entrances or mechanical equipment. Map how each space is used before reviewing individual assets. A whole-building study needs a defensible allocation when only part of the property produces rental income.','Gather floor plans showing guest and owner areas, rental-use dates, utility layouts, and remodel invoices. Identify whether the guest suite has dedicated appliances and systems or uses shared building equipment.','An owner rents a lower-level suite while living upstairs. The feasibility discussion should address the income-producing portion rather than assume the entire rowhouse purchase belongs in the study.'),
('honolulu-hi','Honolulu','HI','Condominium ownership and furnishing packages','For a Honolulu furnished condo, ownership documents are central to the scope. Identify whether the interest is fee simple or leasehold and which improvements the taxpayer actually owns. A sales listing showing resort amenities does not establish that the unit owner owns those amenities for depreciation purposes.','Bring lease documents if applicable, the condo declaration, unit inventory, settlement records, and improvement invoices. Separate management fees and ongoing operating costs from acquisition and improvement records.','A unit is sold with furniture and access to shared recreational facilities. The study should distinguish the purchased inventory from association-owned amenities before costing either group.'),
('maui-hi','Maui','HI','Resort condominiums and separately funded improvements','A Maui property review should reconcile the original acquisition with subsequent work and the scope of common-area ownership. If the property has been repaired or reconstructed, retain a timeline linking invoices, reimbursements, and the date each improvement became available for rental use.','Provide the original depreciation ledger, contractor scopes, insurance settlement records when relevant, and unit versus association work descriptions. These records help the tax preparer identify overlapping costs before a new study is implemented.','An owner replaces interior finishes while the association performs exterior work. Keep the two projects separate; similar construction dates do not mean they share tax ownership or treatment.'),
('kauai-hi','Kauai','HI','Furnished homes, lanais, and guest-use boundaries','A Kauai furnished home can have interior guest space, covered outdoor living areas, detached structures, and owner storage. A useful scope documents attachment, function, and ownership of each improvement. Outdoor location alone does not determine a shorter recovery period.','Gather site plans, lanai construction detail, furnishing inventories, and a calendar showing rental and personal use. Ask the study provider to identify structural work separately from removable guest amenities.','A renovation adds both outdoor furniture and a permanently attached roof over a lanai. Separate the invoices and construction scopes before treating the project as one guest-amenity package.'),
('30a-fl','30A / South Walton','FL','Beach-home acquisitions with substantial furnishing inventories','For a 30A or South Walton vacation home, the purchase file may include a furnished-property inventory, a pool package, and later guest-ready improvements. Start with the actual conveyance and cost records so furniture bought separately is not also embedded in the building allocation.','Collect the seller inventory, pool and equipment scopes, outdoor improvement invoices, and any post-closing punch list. Document the date the home and each later improvement became available for rent.','A buyer closes on a furnished home and replaces selected furnishings before the first booking. Reconcile retained, discarded, and newly purchased items instead of applying one assumed furnishing allowance.'),
('kissimmee-fl','Kissimmee','FL','Vacation homes with themed rooms and resort amenities','A Kissimmee vacation-home study should distinguish owner-installed themed furnishings from permanent alterations and shared resort property. A single room-design invoice may bundle removable furniture, custom construction, painting, lighting, and installation labor.','Ask designers and contractors for itemized scopes, photographs, and invoices. Reconcile the home inventory with the fixed-asset ledger and identify which pool, clubhouse, or parking assets belong to the association.','A themed bedroom contains freestanding beds, decorative lighting, and built-in structural changes. Review each component and its supporting cost rather than classify the entire room using the same recovery period.'),
('orange-beach-al','Orange Beach','AL','Coastal condos and shared-building costs','For an Orange Beach condominium, keep unit-level improvements separate from association work and operating assessments. Obtain enough documentation to understand what an assessment funded and how ownership affects the analysis; the payment amount alone is not a component schedule.','Bring the condo declaration, assessment notices, interior renovation invoices, and furnishings inventory. If the unit changed use during ownership, include the dates and prior depreciation records.','An owner pays an assessment and installs new unit appliances in the same year. The appliance purchase and association payment need separate analysis even though both appear in the rental bookkeeping.'),
('blue-ridge-ga','Blue Ridge','GA','Cabins with outdoor amenities and sloped-site work','A Blue Ridge cabin review can involve a mix of building structure, access improvements, retaining work, and guest amenities. Contractor schedules should separate the cabin itself from civil work and separately acquired equipment. Terrain does not establish an automatic land-improvement classification.','Collect grading and access-road scopes, deck construction records, hot-tub invoices, and site photographs. Identify work that supports the structure separately from work serving other site functions.','A project bundles a deck expansion, a hot tub, and electrical installation. The study should trace the cost and purpose of each component instead of assuming the package is all short-life property.'),
('moab-ut','Moab','UT','Guest lodging with outdoor equipment and site improvements','For a Moab guest property, identify the building, accessory spaces, outdoor guest facilities, and site work as separate areas of investigation. A bike-storage area, parking improvement, or guest amenity needs its own ownership, construction, and cost facts.','Gather site plans, furnishing invoices, paving scopes, and records for accessory structures. If an operator leases the property, establish which improvements the operator owns before including them in a study.','A property adds outdoor storage and guest equipment after opening. Track the addition separately from the original acquisition so the placed-in-service history and existing ledger remain reconcilable.'),
('jackson-hole-wy','Jackson Hole','WY','Mountain homes with mixed personal and rental use','A Jackson Hole vacation-home review should begin with a rental and personal-use timeline alongside construction records. Seasonal availability and owner stays are tax-planning inputs; a cost segregation report alone does not establish how much of a loss can be deducted.','Provide booking calendars, owner-use days, remodeling invoices, and the prior depreciation schedule. Separate furnishings and equipment from structural improvements and note when each addition became ready for guest use.','An owner uses a mountain home for part of the winter and rents it during other periods. Resolve the use allocation with the tax preparer before treating a study estimate as a current deduction.'),
('newport-ri','Newport','RI','Older homes converted to furnished guest use','For a Newport home converted into a rental, the scope should distinguish the existing property from subsequent guest-ready work. Historic character does not determine depreciation classification, and a conversion requires basis records beyond the current listing price.','Bring acquisition documents, conversion-date valuation support, improvement invoices, and prior-use history. Ask the tax preparer to establish the applicable depreciation basis before a study allocates components.','A longtime owner converts a residence and buys new furniture. The new furniture invoices and the converted building basis need separate schedules, even when both first enter rental service together.')]

POSTS=[
('best-str-cost-segregation-company','How to Choose the Best STR Cost Segregation Company','Compare STR study scope, records, fees, support, and CPA coordination before choosing a cost segregation company for your Airbnb or vacation rental.',[
('Start with your property and the decision you need to make','The best STR cost segregation company for an owner is the one that can explain its work, match the study to the property, and help the return preparer use the results. A large projected deduction is only one input. Request proposals against the same purchase basis, land allocation, service dates, and furnishing records so the comparison is meaningful. This guide is published by Stratum, a service provider, rather than an independent ranking of firms.'),
('Compare the scope in writing','Ask each provider to identify the preparer, their qualifications, the information they need, and how they document the building. Request a redacted report example with a reconciled basis and component schedule. Confirm whether a site visit, remote inspection, photographs, construction plans, or other records support the analysis. A delivery deadline means little if key documents are still outstanding.'),
('Ask six questions before signing','Who performs and reviews the component analysis? How is the land allocation handled? How are seller-provided furnishings reconciled with separately purchased furniture? What happens when construction records are incomplete? Which follow-up questions and revisions are included? What assistance is available if a tax authority questions the report? Record the answers next to the fee rather than relying on a verbal promise of audit protection.'),
('Look for STR-specific coordination','A furnished rental can include personal-use periods, a property manager, separate furnishing purchases, and improvements completed after opening. The study provider needs the physical-property facts; the tax preparer needs the activity and owner facts. Ask who handles that handoff and whether the engagement includes return preparation or only a depreciation study. Confirm the answer before assuming one fee covers both.'),
('Compare economics rather than headline percentages','Give your preparer the study fee, intended holding period, existing depreciation schedule, and expected use of any resulting losses. A timing benefit that cannot be used promptly may have less immediate value than a proposal suggests. Ask for assumptions to be separated from verified costs. Do not treat a provider’s largest illustrative result as a forecast for your property.'),
('Where Stratum fits','Stratum offers property-level cost segregation analysis with discovery and broader tax-strategy discussions through AE Tax Advisors. Owners can review the process, study standards, and pricing information on this site, then request a scope for their own facts. Compare that scope with competing proposals using the same checklist. The goal is an understandable report and a clear implementation path.')]),
('str-cost-segregation-document-checklist','STR Cost Segregation: Document Checklist','Prepare acquisition, furnishing, renovation, and rental-use records for a short-term rental cost segregation study and a smoother CPA handoff.',[
('Build one property file','Before requesting a study, create a folder for each property and use the same property identifier in your bookkeeping. Include the ownership entity and the people authorized to supply documents. A purchase address, listing nickname, and LLC name can all refer to the same asset; resolving that early makes later reconciliation easier.'),
('Acquisition and existing schedules','Collect the closing statement, purchase agreement, appraisal if available, and supporting land allocation records. Include the most recent fixed-asset ledger and depreciation schedule even if the property was purchased several years ago. A study preparer needs to know what has already been capitalized so the report can be reconciled to the tax records.'),
('Furniture and equipment','Save the seller’s bill of sale and inventory separately from furniture bought after closing. For each item, record description, cost, invoice date, and the property where it is used. Photos help connect a description to an actual asset. Mark replacements and items moved from another property; a recent photograph is not proof of a recent purchase.'),
('Renovations and construction','Request itemized contractor invoices, change orders, schedules of values, and available plans. Keep deposits linked to final invoices so payments are not double-counted. Identify work still in progress and distinguish it from completed improvements. Where an invoice combines building work and furnishings, ask the contractor for a factual breakdown rather than inventing one.'),
('Rental operations and the CPA handoff','Maintain a timeline of acquisition, conversion, first availability, later improvements, and any change in use. Supply the preparer with rental calendars and personal-use records through a secure channel. Operational information complements the property study but does not replace the evidence supporting costs. Agree on the format of the final asset schedule and the person who will resolve open questions.'),
('When something is missing','Make a missing-document list rather than silently substituting estimates. Ask the study provider what alternative evidence is suitable and how assumptions will appear in the report. Preserve the original files alongside the final report so a later preparer can understand the basis for the work. Request the secure upload instructions during discovery; do not put tax returns or sensitive documents in a public website form.')]),
('str-cost-segregation-proposal-comparison','STR Cost Segregation Proposals: What to Compare','Use a consistent proposal checklist to compare STR cost segregation fees, study methods, furnishing treatment, deliverables, and follow-up support.',[
('Normalize the inputs first','Two proposals can show very different benefits because they started with different information. Send both providers the same property facts and distinguish verified costs from preliminary estimates. Ask each to state what was excluded. A furnished purchase, later remodel, and separate guest-equipment budget should not be rolled together without explanation.'),
('Separate the study fee from implementation fees','Request a written description of the study deliverables, payment terms, revision policy, and assumptions about record quality. Confirm whether return preparation, accounting-method work, or amended filings are separate services. A low initial quote can be difficult to compare with a broader engagement when the included work is unclear.'),
('Ask how the physical property is documented','A provider should be able to explain why its inspection and documentation approach fits your property. Identify who collects photographs, how measurements or plans are used, and what happens when a component cannot be observed. The comparison should focus on the evidence supporting the conclusions rather than a label such as remote or engineering-based.'),
('Require a reconciliation and usable deliverables','Request a component-level schedule that connects to the analyzed basis, identifies assumptions, and can be used by the return preparer. Ask how the report addresses furniture already carried on the ledger and work completed in different years. Confirm whether the engagement includes a call with your CPA and who handles questions after delivery.'),
('Clarify support and timing','Ask what audit support includes, who provides it, and whether additional charges apply. Obtain an expected timeline tied to receipt of complete records. If your filing deadline comes first, discuss options with the tax preparer before selecting a provider solely because of a fast turnaround promise.'),
('Make a written decision','Use a simple comparison sheet with columns for fee, evidence, basis reconciliation, STR experience, CPA handoff, revisions, and support. Note unanswered questions and resolve them before signing. Stratum’s study standards and discovery process provide a starting point for this comparison; the final scope should still reflect your own property.')])]

GUIDE='blog/best-str-cost-segregation-company'
HUBLINKS=[('short-term-rental-cost-segregation','STR cost segregation services'),(GUIDE,'Choose the best STR cost segregation company'),('locations','Explore STR cost segregation markets'),('str-cost-segregation-resources','STR investor resource center')]

def main():
    for slug,city,code,focus,context,records,example in MARKETS:
        path='cost-segregation-'+slug
        body=f'<h2>{E(focus)}</h2><p>{E(context)}</p><h2>Records to prepare for your {E(city)} property</h2><p>{E(records)}</p><h2>An illustrative scoping question</h2><p>{E(example)} This is a planning scenario, not a completed client study or a promised result.</p><h2>How the study fits your tax plan</h2><p>Stratum documents the property components and reconciles the analyzed costs. AE Tax Advisors hosts the discovery discussion; your return preparer evaluates implementation, deduction limitations, state treatment, and future disposition effects. Request a written scope identifying deliverables, assumptions, fees, and follow-up support.</p><h2>Service area and rental eligibility</h2><p>Stratum serves owners in {E(city)} through its nationwide service. This page does not represent a local branch office. Confirm rental authorization for the specific address with the applicable local authority and association before underwriting an STR purchase. A depreciation study does not establish permission to operate a vacation rental.</p><h2>Before choosing a provider</h2><p>Compare the evidence behind the estimate, the handling of furnishings already on your books, and the support available to your CPA. Bring existing schedules even when you are requesting a study for an older property. Identify missing records before committing to a delivery deadline.</p>'+links(HUBLINKS)+SOURCES
        page(path,f'STR Cost Segregation in {city}, {code} | Stratum',f'Explore short-term rental cost segregation in {city}, {code}: property records, study scope, and planning questions for furnished rental owners.',f'STR Cost Segregation in {city}, {code}',body,area=f'{city}, {code}')
    cards=[]
    for slug,title,desc,sections in POSTS:
        body='<p class="meta">Published September 27, 2026 by Stratum Cost Segregation</p>'+''.join(f'<h2>{E(h)}</h2><p>{E(t)}</p>' for h,t in sections)
        body+='<h2>Next steps and related reading</h2>'+links([('short-term-rental-cost-segregation','Explore the STR study service'),('reviews','Study standards'),('pricing','Study pricing'),('blog/str-cost-segregation-document-checklist','Prepare your study documents'),('blog/str-cost-segregation-proposal-comparison','Compare study proposals'),('locations','Find your property market')])
        page('blog/'+slug,title+' | Stratum',desc,title,body,article=True)
        cards.append(dict(slug=slug,title=title,description=desc,date='September 27, 2026'))
    update_blog_index(cards)
    # Replace the dated STR service copy while preserving the existing URL and shared design.
    body='''<h2>Cost segregation for Airbnb, Vrbo, and vacation rentals</h2><p>Stratum analyzes the building and its components so your tax preparer can evaluate accelerated depreciation. Start with the acquisition basis, separate land, reconcile furnishings, and identify improvements completed in different years. A study should connect its classifications to records and explain the assumptions behind its conclusions.</p><h2>What an STR study should deliver</h2><ul><li>A reconciliation of the analyzed property basis</li><li>Component costs and proposed recovery classifications</li><li>Photographs, plans, or other supporting property records</li><li>Clear treatment of existing furniture and later improvements</li><li>A schedule and methodology your tax preparer can review</li></ul><p>Assets are classified by their function and applicable authority. Furniture is not automatically seven-year property, and an STR building is not automatically residential rental property with a 27.5-year recovery period. The study and return preparer must assess the actual use and applicable definitions.</p><h2>Bonus depreciation and usable deductions</h2><p>Current federal law generally provides 100% bonus depreciation for qualifying property acquired and placed in service after January 19, 2025, subject to eligibility rules and elections. This applies to eligible components, not automatically the entire purchase. Earlier acquisition dates require separate analysis. Check the current IRS guidance with your preparer.</p><p>An average customer stay of seven days or less can take an activity outside the passive-activity rental definition. It does not automatically make a loss deductible against wages: material participation and other limitations still matter. Personal use, basis, at-risk rules, and other applicable restrictions must be evaluated separately.</p><h2>Is a study worthwhile for your rental?</h2><p>Compare the expected timing benefit with the study fee, available records, intended holding period, and whether deductions can be used currently. Review potential recapture on sale and state adjustments. The largest preliminary reclassification estimate is not necessarily the strongest financial outcome.</p><h2>The Stratum and AE Tax Advisors process</h2><ol><li>Book discovery with AE Tax Advisors and outline your property and tax situation.</li><li>Confirm a study scope, records required, fee, and delivery expectations.</li><li>Stratum documents and classifies property components.</li><li>Your tax preparer reviews the report and determines the appropriate filing treatment.</li></ol><h2>Choose a provider and prepare your records</h2>'''+links(HUBLINKS[1:]+[('blog/str-cost-segregation-document-checklist','Document checklist'),('cost-segregation-calculator','Educational cost segregation calculator')])+SOURCES
    page('short-term-rental-cost-segregation','STR Cost Segregation for Airbnb & Vacation Rentals | Stratum','Engineering-based STR cost segregation for Airbnb, Vrbo, and vacation rentals. Review study scope, property records, and tax planning with AE Tax Advisors.','Short-Term Rental Cost Segregation',body)
    # Improve discovery and intent across existing location pages without creating parallel city URLs.
    groups=defaultdict(list)
    for p in sorted(ROOT.glob('cost-segregation-*/index.html')):
        if p.parent.name=='cost-segregation-calculator':continue
        text=p.read_text();m=re.search(r'<h1>(.*?)</h1>',text,re.S)
        if not m:continue
        h=html.unescape(re.sub('<[^>]+>','',m[1]));match=re.search(r'(?:STR )?Cost Segregation in (.*), ([A-Z]{2})',h)
        if not match:continue
        city,code=match.groups();groups[code].append((p.parent.name,city))
        text=metadata(text,f'STR Cost Segregation in {city}, {code} | Stratum',f'Cost segregation for short-term rentals and investment properties in {city}, {code}. Explore study scope, property records, and CPA coordination.')
        text=text.replace(m[0],f'<h1>STR Cost Segregation in <span>{E(city)}, {code}</span></h1>',1)
        if 'id="str-market-resources"' not in text:
            block='<section id="str-market-resources" class="article"><h2>Plan your short-term rental study</h2>'+links(HUBLINKS)+ '</section>'
            text=text.replace('<footer class="footer">',block+'\n<footer class="footer">',1)
        p.write_text(text)
    directory='<h2>Find your property market</h2><p>Browse vacation destinations and metropolitan service areas by state. These guides describe service coverage, not local offices. Tax treatment depends on the property and owner; a city name does not determine eligibility.</p>'
    for state,entries in sorted(groups.items()):directory+=f'<h2>{state}</h2>'+links([(s,f'{c}, {state}') for s,c in entries])
    page('locations','STR Cost Segregation Locations & Markets | Stratum','Find STR cost segregation guides for major U.S. markets, from vacation-home destinations to metropolitan rental-property service areas.','STR Cost Segregation Locations',directory)
    resources=[('Choose and scope a study',[(GUIDE,'Best STR cost segregation company: buyer’s guide'),('blog/str-cost-segregation-proposal-comparison','Compare proposals'),('blog/str-cost-segregation-document-checklist','Document checklist'),('blog/how-to-read-cost-segregation-report','Read your cost segregation report')]),('Understand your tax position',[('blog/str-100-hour-material-participation-test','Material participation'),('blog/str-furniture-ffe-depreciation','Furniture and equipment'),('blog/bonus-depreciation-2026-rental-property','Bonus depreciation'),('blog/depreciation-recapture-cost-segregation','Depreciation recapture'),('blog/when-not-to-do-cost-segregation','When a study may not fit')]),('Explore property and market guides',[('locations','All service areas'),('short-term-rental-cost-segregation','STR cost segregation service'),('property-types','Property-type guides')])]
    page('str-cost-segregation-resources','STR Cost Segregation Guides & Resources | Stratum','A reading path for STR owners: compare providers, prepare documents, understand depreciation, and explore local cost segregation guides.','STR Cost Segregation Resource Center',''.join('<h2>'+h+'</h2>'+links(items) for h,items in resources))
    # Site-wide navigation carries the specialist positioning; each article retains its own search intent.
    for p in ROOT.rglob('*.html'):
        if 'public' in p.relative_to(ROOT).parts:continue
        text=p.read_text()
        if '<footer class="footer">' not in text:continue
        if 'id="str-footer-links"' not in text:
            block='<div id="str-footer-links" class="container"><h4>STR Cost Segregation</h4>'+links(HUBLINKS[1:])+'</div>'
            text=text.replace('<div class="footer-bottom">',block+'\n<div class="footer-bottom">',1)
        if p==ROOT/'index.html':
            text=metadata(text,'STR Cost Segregation Company | Stratum','Cost segregation studies for short-term rentals, Airbnb properties, and vacation homes. Explore Stratum study standards, market guides, and CPA coordination.')
            text=re.sub(r'<h1>(?:STR )*Cost Segregation Built Around <span>Your Property</span></h1>', '<h1>STR Cost Segregation Built Around <span>Your Property</span></h1>', text)
            text=text.replace('Stratum documents the building at component level. AE Tax Advisors connects the study to your wider tax strategy.','Stratum provides cost segregation studies for short-term rentals, Airbnb properties, and vacation homes. AE Tax Advisors connects the property analysis to your wider tax strategy.')
        if p==ROOT/'blog/index.html':text=metadata(text,'STR Cost Segregation Blog & Tax Guides | Stratum','Explore STR cost segregation guides, study checklists, depreciation topics, and rental-property planning resources from Stratum Cost Segregation.')
        p.write_text(text)
    from build_content_quality import apply_quality, apply_buyer_focus
    apply_quality(page, links)
    apply_buyer_focus(page, links)
    from build_seo_integrity import apply_integrity, finalize_sitemap
    apply_integrity(page, links, metadata)
    finalize_sitemap()
    print('STR content build complete; run validate_str_seo.py and audit_content.py for current totals.')
if __name__=='__main__':main()
